### ISSUE TITLE
DHT22:__init__() call to parent constructor missing positional parameter unit_index.

### ISSUE THREAD

**Issue by jfmauzey** [kevinkk525/pysmartnode#11]
In module pysmartnode.components.sensors in file dht22.py line 64.
Argument list in call to super() is missing the third argument _unit_index. This causes a runtime error
to be thrown. Simply add the missing parameter which is defined locally to the call and all is well.

**Comment by kevinkk525** [comment]
Thanks a lot for reporting this issue!
It should be fixed by https://github.com/kevinkk525/pysmartnode/commit/c48251dff6420bafa337b8a74d5bc684acf81a15

**Comment by kevinkk525** [comment]
Oh and congrats on opening your first issue! And the first issue on my project :)
