### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)

### ISSUE THREAD

**Issue by palmtreefrb** [kevinkk525/pysmartnode#20]
This occured one time last night...

[2020-04-12 02:03:53] [STATS0] [info] 67920
[2020-04-12 02:04:03] [STATS0] [info] 67920
[2020-04-12 02:04:14] [STATS0] [info] 67920
[2020-04-12 02:04:24] [STATS0] [info] 67920
[2020-04-12 02:04:35] [STATS0] [info] 67936
[2020-04-12 02:04:45] [STATS0] [info] 67920
[2020-04-12 02:04:56] [STATS0] [info] 67920
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: BREAK instr 
Core 1 register dump:
PC      : 0x400803c0  PS      : 0x00060836  A0      : 0x00000000  A1      : 0x3ffcfe90  
A2      : 0x3ffc1eb4  A3      : 0x3ffba28c  A4      : 0x3ffe5990  A5      : 0x3ffd00a0  
A6      : 0x00000002  A7      : 0x3ffd0060  A8      : 0x00060023  A9      : 0x00000000  
A10     : 0x3ffc294c  A11     : 0x3ffc2a00  A12     : 0x80091c3c  A13     : 0x3ffbb260  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000016  EXCCAUSE: 0x00000001  
EXCVADDR: 0xffffffd0  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000

Backtrace: 0x400803bd:0x3ffcfe90

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5240
load:0x40078000,len:12880
ho 0 tail 12 room 4
load:0x40080400,len:3484
entry 0x40080630
I (551) cpu_start: Pro cpu up.
I (551) cpu_start: Application information:
I (551) cpu_start: Compile time:     Apr 11 2020 18:24:42
I (554) cpu_start: ELF file SHA256:  0000000000000000...
I (560) cpu_start: ESP-IDF:          v4.0
I (565) cpu_start: Starting app cpu, entry point is 0x40082e74
I (556) cpu_start: App cpu up.
I (575) heap_init: Initializing. RAM available for dynamic allocation:
I (582) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (588) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (594) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (601) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (607) heap_init: At 3FFCCA70 len 00013590 (77 KiB): DRAM
I (613) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (619) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (626) heap_init: At 4009EA08 len 000015F8 (5 KiB): IRAM
I (632) cpu_start: Pro cpu start user code
I (650) spi_flash: detected chip: generic
I (651) spi_flash: flash io: dio
I (651) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
109952
105744
PySmartNode version 610 started
I (1390) modsocket: Initializing
I (1460) wifi: wifi driver task: 3ffd2ef4, prio:23, stack:3584, core=0
I (3580) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (3590) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (3620) wifi: wifi firmware version: 581f422
I (3620) wifi: config NVS flash: enabled
I (3620) wifi: config nano formating: disabled
I (3620) wifi: Init dynamic tx buffer num: 32
I (3620) wifi: Init data frame dynamic rx buffer num: 32
I (3630) wifi: Init management frame dynamic rx buffer num: 32
I (3630) wifi: Init management short buffer num: 32
I (3640) wifi: Init static rx buffer size: 1600
I (3640) wifi: Init static rx buffer num: 10
I (3640) wifi: Init dynamic rx buffer num: 32
I (3760) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (3760) wifi: mode : sta (4c:11:ae:71:39:94)
I (3760) wifi: STA_START
free ram 90112
[2020-04-12 02:04:20] [DS18] [info] Sensor DS18 will publish readings for temperature to topic breweryaiss/4c11ae713994/DS18
free ram 70848
Starting uasyncio loop
[2020-04-12 02:04:20] [config] [info] Added module STATS version 1.71 as component STATS
I (6050) wifi: new:<4,0>, old:<1,0>, ap:<255,255>, sta:<4,0>, prof:1
I (6900) wifi: state: init -> auth (b0)
I (6900) wifi: state: auth -> assoc (0)
I (6910) wifi: state: assoc -> run (10)
[2020-04-12 02:04:22] [DS18] [info] Found new ds18: 28F58C4592030282
I (7920) wifi: connected with ASUS_68_2G, aid = 1, channel 4, BW20, bssid = b0:6e:bf:de:6f:68
I (7920) wifi: security type: 3, phy: bgn, rssi: -23
I (7920) wifi: pm start, type: 1

I (7930) network: CONNECTED
I (7940) wifi: AP's beacon interval = 102400 us, DTIM period = 3
I (8510) tcpip_adapter: sta ip: 192.168.1.231, mask: 255.255.255.0, gw: 192.168.1.1
I (8510) network: GOT_IP
[2020-04-12 02:04:26] [STATS0] [info] 67792
[2020-04-12 02:04:29] [MQTT] [info] mqtt connected
[2020-04-12 02:04:29] [MQTT] [info] WIFI state True
FTP-Server active
Connected, local ip '192.168.1.231'
Synchronize time from NTP server ...
FTP Server started on  192.168.1.231
Set time to (2020, 4, 12, 2, 5, 19, 6, 103)
[2020-04-12 02:05:19] [MQTT] [info] (sysname='esp32', nodename='esp32', release='1.12.0', version='v1.12-351-gbd5633778-dirty on 2020-04-11', machine='ESP32 module with ESP32')
[2020-04-12 02:05:19] [config] [info] Added module DS18 version 3.4 as component ds18
[2020-04-12 02:05:20] [MQTT] [info] Client version: 610
[2020-04-12 02:05:20] [config] [info] Added module GPIO version 1.11 as component relay
[2020-04-12 02:05:23] [config] [info] Added module Climate version 0.92 as component fermenter
[2020-04-12 02:05:39] [STATS0] [info] 67920
[2020-04-12 02:05:50] [STATS0] [info] 67920
[2020-04-12 02:06:00] [STATS0] [info] 67920
[2020-04-12 02:06:10] [STATS0] [info] 67920

**Comment by kevinkk525** [comment]
yeah the esp32 isn't the most reliable platform. I get these crashes too from time to time. I don't think they are in any way related to my project.

**Comment by palmtreefrb** [comment]
Yep, but watchdog took care and reset the device :-)
