### ISSUE TITLE
ESP8266 @micropython.native

### ISSUE THREAD

**Issue by palmtreefrb** [kevinkk525/pysmartnode#23]
Not able to freeze mqtt.py, seems to fail because of "@micropython.native"

error compiling /home/fredrick/Development/micropython/micropython-1.12/lib/pysmartnode-8266/pysmartnode/networking/mqtt.py:
mpy-cross: ../py/asmbase.c:82: mp_asm_base_label_assign: Assertion `as->label_offsets[label] == as->code_offset' failed.

**Comment by kevinkk525** [comment]
Yeah some recent changes made this not work anymore. Remove the native decorator. I only added it for speed. 
Asked in the forum the last days too but there doesn't seem to be an easy way out at the moment. Will go without it. I will push an update today, have been working on some changes the last days.

**Comment by kevinkk525** [comment]
With the PR merged, this issue is fixed.
But should you have any problems or questions, feel free to answer to this issue or create a new one.
